### PR TITLE
Web page rework

### PR DESCRIPTION
**Pull request by MrSnowball-dev**
Willing to help to build a more suitable web page for such a project :)

### CODE REVIEW

**Comment by MrSnowball-dev** [comment]
Buttons are now on par sith toggles: looks pretty :)
👍

**Comment by MrSnowball-dev** [comment]
There was some conflict in HTML which I resolved. Honestly idk what was wrong. 
@BotoX could you merge this pull request, please?

**Comment by Toxblh** [comment]
@BotoX Could you check the PR?

**Comment by MrSnowball-dev** [comment]
I am away for a couple of days, will commit recent changes next week.

**Pull request closed without merging**
